### ISSUE TITLE
HomeAssistant Modbus Fronius modify parameters

### ISSUE THREAD

**Issue by dm82m** [bigramonk/byd_charging#1]
Hey @bigramonk 

i want to forbid the usage of my byd battery within my house during I fullspeed charge my electric car. To achieve that I would set the Soc minimum on fronius with modbus tcp on home assistant.

Could you help me achieving this with your scripts or at least point me in the right direction?

help is heavily appreciated!

dirk

**Comment by dm82m** [comment]
okay with:

```
  - service: modbus.write_register
    data:
      slave: 1
      address: 40350
      value: 9900
      hub: gen24
```

I can set it to 99 and with:

```
  - service: modbus.write_register
    data:
      slave: 1
      address: 40350
      value: 500
      hub: gen24
```

I can set it back to 5.

BUT: this change is not reflected within the UI of the fronius. That is confusing me!
